### ISSUE TITLE
Custom style - no secondary layout

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#15] opened 2018-05-23 11:04 UTC
Steps:
* Settings
* Appearance & Layouts
* Customised input style
* New
* **Romanian** / **Dvorak**
* Save -> Use
* Try to use the keyboard
* See that keys don't show secondary chars (eg. - or _ or @ etc)
* See that keys don't react to long press

(Google keyboard does not have this issue)

**Comment by rkkr** [comment] 2018-06-02 15:49
Duplicate of #16

**Closed by rkkr** 2018-06-02 15:49 UTC

**Comment by licaon-kter** [comment] 2018-06-02 15:54
Please read my post and reopen, I've said: 
```
Romanian / Dvorak
Save -> **Use**
```

Use takes me to the layout activation view....where I've activated it...

**Comment by rkkr** [comment] 2018-06-02 16:03
I've enabled it in Language settings. Special keys are shown and long-press works.

![image](https://user-images.githubusercontent.com/3480123/40878305-a696dbae-6697-11e8-86eb-748223174ee8.png)

**Comment by licaon-kter** [comment] 2018-06-02 16:14
Now select plain English....notice how _secondary layout chars_ are shown **on keys** ?

Notice how long pressing *other* keys than a,e,i,t,s brings chars like - _ / ?

Please reopen, here's the layout in Google Keyboard 5.1.23:

![img_20180602_191146](https://user-images.githubusercontent.com/2282799/40878388-e95ef56a-667f-11e8-847d-6625557cd5df.jpg)

By comparison choosing a random layout like Russian has a 1:1 layout like in Google Keyboard, not sure why Romanian is broken.

**Comment by rkkr** [comment] 2018-06-02 16:33
It's not the Romanian that is broken, it's Dvorak. And it's not broken, it's just not implemented. Special characters on keys are not shown in AOSP. I only added them to QWERTY. If you want them in Dvorak, you are welcome to do it yourself :)

**Comment by licaon-kter** [comment] 2018-06-02 17:48
Do link me where exactly, thanks.

**Comment by rkkr** [comment] 2018-06-03 05:27
showNumberRow variable in [rowkeys_qwertyX.xml](https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/rowkeys_qwerty1.xml). [rowkeys_dvorakX.xml](For https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/rowkeys_dvorak1.xml) and the remaining ones it's not used. keyHintLabel and additionalMoreKeys is what shows the secondary character.
