### ISSUE TITLE
[Feature Request] Emojis

### ISSUE THREAD

**Issue by MiMoHo** [rkkr/simple-keyboard#299] opened 2021-07-11 16:45 UTC
A simple keyboard must not miss what is broadly used among keyboard users: emojis. Maybe not everyone needs or uses them, but having an option to toggle on or off emojis in the Simple Keyboard settings would make it the ultimate keyboard choice to me. Not every app has a built-in emoji button like WhatsApp, therefore, I find myself several times a day copying emojis from WhatsApp into the clipboard in order to paste it in the text field of another app as you want the Simple Keyboard to stay simple. Yes, indeed, but please support relevant unicodes!

**Comment by licaon-kter** [comment] 2021-07-11 17:21
/close as duplicate of #13

Use OpenBoard or FlorisBoard

**Closed** 2021-07-14 05:19 UTC
